project:
  title: @project.name@
  description: @project.description@
  version: @project.version@

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/eucomida-db
    username: eucomida
    password: eucomida
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
server:
  port: 8081

eucomida:
  config:
    security:
      issuer: euComida
      jwt:
        secret: ${JWT_SECRET:super-secret-key-that-should-be-in-key-vault}
        expiration: 86400000