services:
  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: eucomida-db
      POSTGRES_USER: eucomida
      POSTGRES_PASSWORD: eucomida
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network1
volumes:
  postgres_data:
networks:
  network1:
    name: bridge-network
    driver: bridge